---
# Development role handlers

- name: restart rootless docker
  systemd:
    name: docker
    state: restarted
    scope: user

- name: restart systemd-resolved
  become: true
  systemd:
    name: systemd-resolved
    state: restarted
