---
# Handlers for desktop role

- name: restart NetworkManager
  become: true
  systemd:
    name: NetworkManager
    state: restarted

- name: reload udev rules
  become: true
  shell: |
    udevadm control --reload-rules
    udevadm trigger --subsystem-match=net

- name: rebuild initramfs
  become: true
  command: mkinitcpio -P
  when: ansible_facts['virtualization_type'] != "docker"
